# file: .travis.yml
language: objective-c
osx_image: xcode8
xcode_project: TableColumnChooser.xcodeproj
xcode_scheme: TableColumnChooser

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
- gem install xcpretty -N

script:

- xctool -project TableColumnChooser.xcodeproj -scheme 'TableColumnChooser' test | xcpretty -c


